import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from 'react';
// @ts-ignore
import styles from '../styles/Index.module.less'
import {DatePicker} from 'antd'
import NavBar from '../components/navbar'
import {RightOutlined} from '@ant-design/icons'
import {Header} from "antd/es/layout/layout";
const menuList:any[]=[
    {
        title:'首页',
        icon:'',
        href:'/',
        children:[]
    },
    {
        title:'小工具',
        icon:'',
        href:'/tool',
        children:[]
    },
    {
        title:'读文章',
        icon:'',
        href:'/article',
        children:[]
    },
    {
        title:'写心情',
        icon:'',
        href:'/mood',
        children:[]
    },
    {
        title:'爱分享',
        icon:'',
        href:'/share',
        children:[]
    },
]
import Link from 'next/link'
export default function Index() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <header className="header">
                <NavBar menu={menuList}/>
            </header>
            <main className="container">
                <div className={`row ${styles.part1}`}>
                    <div className="col-lg-8">
                        <div className="card">
                            <div className="card-header">
                                BING
                            </div>
                            <div className={`carousel slide ${styles.carouselWrap}`} data-bs-ride="carousel">
                                <div className="carousel-indicators">
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                                    className="active" aria-current="true" aria-label="Slide 1"></button>
                        </div>
                                <div className={`carousel-inner ${styles.carouselContent}`}>
                                    <div className={`carousel-item active ${styles.carouselItem}`}>
                                        <img  className={`d-block w-100 ${styles.img}`} src="https://cn.bing.com/th?id=OHR.DancingTrees_ZH-CN2946844631_800x600.jpg"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-4">
                        <div className={`card ${styles.rightCard}`}>
                            <div className="card-header">
                                热门资讯
                            </div>
                            <ul className="list-group list-group-flush">
                                <li className="list-group-item">
                                    <a href="https://www.baidu.com/"
                                       className={`${styles.hotContent} ${styles.linkItem}`}
                                       rel="external nofollow noopener noreferrer"
                                       target="_blank">
                                        <p className={styles.hotTitle}>
                                            An itemAn itemAn itemAn itemAn itemAn itemAn itemAn item
                                        </p>
                                        <RightOutlined/>
                                    </a>
                                </li>
                                <li className="list-group-item">A second item</li>
                                <li className="list-group-item">A third item</li>
                            </ul>
                        </div>
                        <div className={`card ${styles.rightCard}`}>
                            <div className="card-header">
                                热门文章
                            </div>
                            <ul className="list-group list-group-flush">
                                <li className="list-group-item">
                                    <a href="https://www.baidu.com/"
                                       className={`${styles.hotContent} ${styles.linkItem}`}
                                       rel="external nofollow noopener noreferrer"
                                       target="_blank">
                                        <p className={styles.hotTitle}>
                                            An itemAn itemAn itemAn itemAn itemAn itemAn itemAn item
                                        </p>
                                        <RightOutlined/>
                                    </a>
                                </li>
                                <li className="list-group-item">A second item</li>
                                <li className="list-group-item">A third item</li>
                            </ul>
                        </div>
                        <div className={`card ${styles.rightCard}`}>
                            <div className="card-header">
                                每日一言
                            </div>
                            <div className="card-body">
                                {/*<blockquote className="blockquote mb-0"></blockquote>*/}
                                <p>A well-known quote, contained in a blockquote element.</p>
                                <footer className="blockquote-footer">Someone famous in <cite
                                    title="Source Title">Source Title</cite></footer>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={`card ${styles.part2}`}>
                    <div className={`card-header ${styles.linkItem}`}>
                        <span>常用工具</span>
                        <Link href="/tool">
                            <a  className={styles.linkItem}>more <RightOutlined/></a>
                        </Link>
                    </div>
                    <div className={`card-body`}>
                        <div className={`row`}>
                            <div className="col-lg-4">
                                <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Card title</h5>
                                        <p className="card-text">This is a wider card with supporting text below as a natural
                                            lead-in to additional content. This content is a little bit longer.</p>
                                        <p className="card-text"><small className="text-muted">Last updated 3 mins ago</small>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-4">
                                <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Card title</h5>
                                        <p className="card-text">This is a wider card with supporting text below as a natural
                                            lead-in to additional content. This content is a little bit longer.</p>
                                        <p className="card-text"><small className="text-muted">Last updated 3 mins ago</small>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-4">
                                <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Card title</h5>
                                        <p className="card-text">This is a wider card with supporting text below as a natural
                                            lead-in to additional content. This content is a little bit longer.</p>
                                        <p className="card-text"><small className="text-muted">Last updated 3 mins ago</small>
                                        </p>
                                    </div>
                                </div>
                            </div>
                     
                        </div>
                    </div>
                </div>
            </main>
            
        </div>
    )
}
